In [ ]:
%pip install jupysql pandas matplotlib duckdb-engine

In [3]:
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

In [ ]:
import duckdb
import pandas as pd

# %reload_ext sql
%load_ext sql
conn = duckdb.connect()
%sql conn --alias duckdb

In [ ]:
# Or use SQLAlchemy
# %sql duckdb:///file.db
# %sql duckdb:///:memory:

In [26]:
%%sql
CREATE or replace temp TABLE t3 AS
    SELECT 42 AS i, 84 AS j;

Empty DataFrame
Columns: [Success]
Index: []

In [28]:
%%sql
describe t3;

Empty DataFrame
Columns: [Success]
Index: []